def game_hash
hashketball ={
  :home =>{
    :team_name => "TODO",
    :colors=>["TODO"],
    :players =>[
      {:player_name => "Alan Anderson",
      :number => 0,
      :shoe => 16,
      :points => 22,
      :rebounds => 12,
      :assists => 12,
      :steals => 3,
      :blocks => 1, 
      :slam_dunks => 1},
      {:player_name => "Alan Anderson",
      :number => 0,
      :shoe => 16,
      :points => 22,
      :rebounds => 12,
      :assists => 12,
      :steals => 3,
      :blocks => 1, 
      :slam_dunks => 1},
      {:player_name => "Alan Anderson",
      :number => 0,
      :shoe => 16,
      :points => 22,
      :rebounds => 12,
      :assists => 12,
      :steals => 3,
      :blocks => 1, 
      :slam_dunks => 1},
      {:player_name => "Alan Anderson",
      :number => 0,
      :shoe => 16,
      :points => 22,
      :rebounds => 12,
      :assists => 12,
      :steals => 3,
      :blocks => 1, 
      :slam_dunks => 1},
      {:player_name => "Alan Anderson",
      :number => 0,
      :shoe => 16,
      :points => 22,
      :rebounds => 12,
      :assists => 12,
      :steals => 3,
      :blocks => 1, 
      :slam_dunks => 1}],
  },
    
  
  :away =>{}
}

end
